apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alloy
  - cert-manager
  - cilium
  - ddns
  - grafana
  - kube-vip
  - loki
  - rook-ceph
  - velero
  - victoria-metrics
