apiVersion: v1
kind: Secret
metadata:
    name: velero-aws-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:gqKx8LKnyT+pardxcEOY2xN1gG7Vme6aRCYCqdg+9+xl3r4fFuN1v6qfFq7zwhcRnx4Y7eN/Nwq5gvNZ1ZOt8jnsru/qyTRhi0q64oNhlVkNZQORaY0o8EpeM5X62URUDZI5MYVWCn+XxQARay8YSg==,iv:Cpg05KIVJHRazswW3n0lKwwyPxUIdmGwOwqeW52C4DU=,tag:o2b+jyLIaKVgBhUhdr06yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TlhjNWxtQ1hJbEVsMDE1
            U2FiSnhoTHlCY2FkeWtnYUZoMUNlKzJWcmpVCmNnaWFZZUNCLzJiUnNYSVkxQW9V
            MUJuVVpzdXhVRzNYbm5wbE43VEw0MkkKLS0tIHZ5THI0T1hqdXI5ZTE2UDJNR1VM
            ZE8yd3lwRkVtMXpOVGV1VkpkU1dnSnMKK6qMa2IwCPLNEHnlvRVRjMcTRSbAl6vs
            DHhaPG4JM6WCWCtVk4qTun3s74Zhn5xn8y4bMCxSRn/CRVONmEZp8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaFdJcHNBb2taVGExSmZC
            WURsVGVlVmZKMEFja0VESW9VeDkwaXZrc1ZzCjIwMm1VV2k4OEhnWkZqNHFSUFR0
            WnIrZjBtQVRiODBxejB5VURRTnpNSkkKLS0tIHBNVmtvMFlXUWRwOWI5azJHbzc2
            RVNjdDZFUUNiTG9JVlNHbkhXMmJhZ3MKG0w5f8+yJnnGR6BG2VSLlwxs9UxWrqzS
            yIz8HUFNGUxR4AuOCIyrHl4LC9YDGt9tSfwLVYmFr7+jfqlg7D7Jog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T18:02:45Z"
    mac: ENC[AES256_GCM,data:lYcLfidPWCLKwM5iLIbIbAezQpm9up9FOAMJv2GDBg8wSff8VNA6iEWSqx1CAQoTvmUFJRCgFWTLs/Z9dbUeDUIhyzDV+Jke8HQRJj4WGq2Ef/j2kVqT7t2EZpGDt4GAxVusmgiCxs3BLAIDW4se4WXW3bKmhfxJvxSLMGrrtx8=,iv:wrBfUWub22/nZBNogO/0FTGqC9/9n7ytE8RjvO1P3/4=,tag:Sz8TrpnL57lr/amDAQnZXw==,type:str]
    version: 3.13.2
