apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:jBmF2ZJY5w==,iv:SCVHT8qD9k/iynGNIH5OKoRLAKYTIY9cJpOD8okiqLU=,tag:dlE5OI6/os8eKAB17jw8fw==,type:str]
    admin-password: ENC[AES256_GCM,data:Am3wRUMZboHF1Y/eBeOVs9+R9aaWgV4+xHj6rQJPeWgVyZePLz5xRg==,iv:MFqLMjamZnJBDWKM7SPfN/pD3eBmfv10sm43KkcnZSQ=,tag:4+hOoQkFfvbRclJBb4sSTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa2YrclJZSVFuempUcjEz
            Uk9yUEdTd3ZZS0JwSk5tWVN3WFBsYjZFeEIwClprQ1NGTlVucWl0Zk80aTQvOExv
            aENFck5TaUMwNFV1aFQzbGF2bHArdEUKLS0tIFBsNTBZTENSRkYrd3dwbEhKQjdK
            YnJHSHpIMEg4anhSOS9CbVBmTldrVXMKXa48QvPh9ZAJbsYN/k7iZDpGu9epHQgl
            3iIeOO+2iYiHSe0Ps7F36p0ky3w869WKnC/fscGb+VNEiA2OImL52A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONU9DSmFtWGtxSTVUcCtr
            VUJ4SGM1ak5rMjJLRlBLVXowaUhTUGdESEU4ClgrVCttVnZUOTRWakRTYWYrOVJH
            SnBHaGNWcGNvZll1NUFBRTFGaHNzWlkKLS0tIGJ4VzB4a2Z3MENFVDBWQmNLVmMx
            c0VuWlExdzJNYWp2eGg2ZG5jNjIxM3MKrSvVmz8AC808qTPtVsZL/UzLOCj9+zkX
            nIzuuAGh3pOPe2KOtGB68cVHUYv/VDlzk/LLOIY6iMiC0csbg+qEgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T12:36:54Z"
    mac: ENC[AES256_GCM,data:aVUe/Uw0uh4jJrF5nol31dFRJW1CPRyaaknEn/tbq/7g4XniUzxY6k4ja/fDiQJzC1Ut95vxgx+W6hXdc3sdLumZLTaqDDiYH4Ln+jYZWu05SlKybCAkLN31ssEzupKeaFdWQnHqX8KNQ8UM3CJjnPFk+Vo7BniwcReUTukwnZA=,iv:u74lh3+dfXte5W84KykTUONMQfeRLBuAkTJ2NfU8bek=,tag:GvUlM3rTAu1KcOGdoILyYg==,type:str]
    version: 3.13.3
