apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-trixie
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie@sha256:771f9eab5225587af259d84680cc69a5b6e374ac32bb24effafde1f3368a1241
