apiVersion: v1
kind: Secret
metadata:
    name: minecraft-backup
    namespace: minecraft
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Rqu5Mjk1KXFtcGHB05qHTrJwNpppDdbKjgUxJU1X66x8dI1yoYGkYuI1pZA04TbQ/5swMuS9jwLLJn6fssJlckaT3SGDSoqy0lC+6AhiIis=,iv:MimK4EQVUzw3T8N8XflEqhMjTtusAYUMrmEYJdUOgqA=,tag:YzrwwfOET54r5Vm3mv0DgA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dS8pc3GtKdn9PDhvrqjOYvQrQ3Q=,iv:2w1O8q+hAdA22NfgWzhimaCwl1MWPaeI5fuU0T3wSiA=,tag:4NMRImmcceE1A5fZjTEllQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GzKwgt7EJKt5SBMBloLIbA8VH8WtEz/P/nsasxllzUYGca0/uqf9Nw==,iv:gSTkGkunCW19RjRUe5NvgT74de/q2HCcIrkHjkpwdEM=,tag:fq6BpDz9kD8L9TEOW4YJsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVlNRZFFpcTVLQ04yZUo3
            bVFWNzF5ZHZyN2NLeU96N1diL0thTEJaU0FVCitFRVZXRUlNMXd5TkUvbEJzbFdj
            OVRnTEplVWlDUnFhdGhHbHkyL1dYZncKLS0tIEw5bWJxRGR5WXBRcVUzd0RNa2Np
            ZURRQUlsN0NJeDFNWGRoY1BYaExIM1EKgk2qYEoaojLGoPRSTzPIEK2MceZiaWxi
            7k7v8+f/3UArl6PWVBSAkUUEecDJUMhuZitpJ00C5Y+P3QbWDSszWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTVBQOVZiZWdOUkQ0MkE2
            OElKZ2M2eHRXU3Q3ek96RFB2TDQrbDNWUGdvCkE4R3d5cVowV2Z6L0lOTGsrT211
            Sm1MMGRLME8ycFRYeXJrc214OXZhQ1UKLS0tIEFRZmg2eEZiOE4rNWJ2K1NHL3Jv
            Q3RzOTVkaWJjcE9DMXAwQkFJanJvY0EKeKLyru2IWfJkWqVE93Kt2Zp+B+V6suBz
            m12yspK6kVNdaQr6HQrECDL0w2Pqv1utwucMGXbGrmWrkaL9S7m9Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:45:07Z"
    mac: ENC[AES256_GCM,data:Zw+PCE2EnQBStOcwrseaz1ODax/6AczEuREjIe+qJB+TQMMJvxbNex9rZrv/ed5/5sDevDRNxhZyhvxTPxrDN7KQLt4Lzs9pIhtfeYErpoYf5Qw/fWsiy55Kqn4HucuSVCBp4g6ZZdfCwukJKQPRK1LGhWrzt+h5/bmkomXs9dE=,iv:eK5cr6+Wm/oUdJMW88rLKWXcT391W+CURNwyHOwGeAs=,tag:POqCqhUlyEIw4FS45NobHA==,type:str]
    version: 3.13.3
