apiVersion: v1
kind: Secret
metadata:
    name: minecraft
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:AXadURP7y0UuIWC4MmRT5MQDDPg+CW9Ymj+Tg3jrCmPMkmQMd8kpPQnYFFs2LZXCPXMjh6fPgm2BCrF9TfwHmssy/uaxfGJIwmLIYczCMx8=,iv:Ba5oUwHt7Kqz/cBSfIorFA9Zhqe7NwlnmRQqPeKauP8=,tag:ORirzWqxgufSO+b/1OLkqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSDc2WHJxaFBBZ2dTVkc1
            bkZhMlNBb0M1K1ZuVFBjaGQ4VlZ4RHhxU1ZzClVBbXE5VG41djBhRHR3OGRwMCsx
            SG45ZXcxOE1YWDNjVCt1ZTVJUTQvN0kKLS0tIDF2Znd4ejVmZ0lqU2RsSGpzMk9o
            bkRSVUJNV1J1SHJJTGlMbUxPVHdzSE0KAkQ22bs5Vx93F67L9xKZ+aPpp1KvbldO
            Rb213lNRhK+k6O5FVIo+UQliJRIvJlqFCwnH9cXNNOnLLEUYs+wYPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSGpkeFM0SzFzTFlwUDlW
            VXFPSS9KMW14NU5sdVBMRU82V1NPQVprTDFJCnkxbThUY3FWNTJBVENuaDNONHFB
            SFhCc2k5c1Y1M1pzaFB5ejBwMUxiQ28KLS0tIEpIYU5uMW9LRGtaTE8rdzR5eG8z
            Y29ocTVSc0ZYaHlSNEVRVlNJcXh3RE0KkRwgtsWUrTe8IW/prRRT4lgFbA1vs3jL
            TLTQy36GwCPByswoPJMuqtpsh+ojyeQtehCTNb83mkI++tpsMtcLfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T21:44:43Z"
    mac: ENC[AES256_GCM,data:VUrRPUtXN/BJCtZ5I2tPnYn3Jhr93CTjnQUBJgnkLcKnq01NyXKAZdN6EMnh7JmC+KfUCsUIeiq5vVMT34tgPuEJuJ0D2vXaSY+VNc5YSwz9nDoINvJi6YP/2y8fLZSk/fa51/cLUk7kEfm327wYl5SMYV9J9G4YIl7z51xh0j0=,iv:dcR8eSgO4AYXQXoRxsuZunM68vCZHB0JpGjL9prbYms=,tag:PqyQMzbX/a29LL1rCvMysw==,type:str]
    version: 3.13.3
