apiVersion: v1
kind: Secret
metadata:
    name: minecraft
    namespace: minecraft
type: Opaque
stringData:
    RCON_PASSWORD: ENC[AES256_GCM,data:5Y+4ZgIzLl1QKa9yINQPWcEMomQ1qBTHw8X6ockuNhI=,iv:jWdtG0RVA1xUizGFvENsvPFNeptdaa29VCDyUO2/1q0=,tag:oqL+n3qeb5h9pGa0lsL0eA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDblZVdlhjVnFlRVF0Zncz
            UU1rOGlRcXRzQWxMTUhNU3plSkcyOTNkbFY0CjQ5MnAvSnRFWnVPZFZwdHp5aTdY
            ZnM4N3hRZkNwRXltL0h3QjUvM29tdVkKLS0tIG9BeEZJQkc2ekdKYk5BckpnQlFB
            WUowNktqbUIxZkNMS09FOURaUzErR1EKWv6f24iRByPjg57jEgl82PEJv80IXvi5
            7M7otte+1WUciDLPZscFqNhfY2q6ccx2FHflVsbs1Rv4Oh7WD7e8Vg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0tKYkU4d2lSb1ZDTXpv
            VTlaNjdnNXBXbFBmUEF0N29FT0JiRUJKTkRBClZYaEtUK0sxdTFmanhJbHlUb240
            S2c0MmFMWHMzZnBzcHIxTE1EL3Nxd3MKLS0tIHZ1ek9nNXpQWkoyRjhTVzlMc0s5
            S3o0RWtmYzlSTTdYTzZySCtyS3lGeDAKOklIHAZiEZwpCAlCAeV3nXjyJTRC5wBO
            hQ9rdUFzqOHcMPBnOHU1djA0FiWITNM6w0BqK1m79SRGD9fe7umTpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T15:24:28Z"
    mac: ENC[AES256_GCM,data:PJ1iNpNsP0tzoiXrguPauhfo4Ir7sWZZJHoRpR134xF9XVV3Sm3cxEMw7Rzgqvi1360iLBJyoAgR/JBOTdaCPWx+w5476hqa3kLiv38Rf1laRr5t2ALIdodsyHo3/cFODUk5S2fDdIpUjKrMjI04v4ssqsDcKsXqjS25eT0hEZA=,iv:Sd4TPSGYT6qX3UQVT8ERgX2kpN/kGZZ4IoJKu21b0fU=,tag:nAlQCL7AIK/D9HjNKEvofQ==,type:str]
    version: 3.13.2
