apiVersion: v1
kind: Service
metadata:
  name: mc
  namespace: minecraft
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minecraft-server
  ports:
    - name: minecraft
      port: 25565
      targetPort: minecraft
    - name: metrics
      port: 8080
      targetPort: metrics
