apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.sops.yaml
- postgres-backup-secret.sops.yaml
- postgres-objectstore.yaml
- postgres-cluster.yaml
- postgres-scheduled-backup.yaml
- postgres-scrape.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- network-policy.yaml
- postgres-network-policy.yaml
