apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-pg-backup
    namespace: vaultwarden
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:rvVaeSSig1vdiSLpJnhYJigsI8Q=,iv:L3YyD7pK1j4+zoZJOpCBWEQoYfdRqLKmdhopDI8m7EU=,tag:ZccqE7eky+byl46/NaZQYQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:d0h98Ks6Q2wU5Zb1T2JAWO96ZHQXCnV6oqRle31ZjaGbZ4NUcyqWKw==,iv:ZmBwpM9ZrXAWPCkuloTF76jMRvZQToZZyzU/RfT2USI=,tag:OgTJE7VjI07bl3yzJ3y9rg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:w744x774E2PT,iv:55EhsfURIWmOzUirTs+vHaO8yXl7FkCB2u64fCpHNL0=,tag:+XfK/wXzp8pCAZ9Y3c0JEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcno1VmpPUnZycmE3NU9U
            OFVGNVZER2x5T1NBcGU3U3BJazAxQkRHeG53CjZhUlhzaVZiZmZDUFlDVEFvNlFk
            K08yZ3pDaGFMQjhWcGk5dlhNK2UzbGMKLS0tIHFBZ2dGMWlRYlZEanY3dUE1Vlg3
            ZS8xRENzR1BjUEdjRE1xUUFBWGVxU1UKEeCctwp17uAEIlklbJG66V0v8v+VrJZW
            S9fKhMjikg//OyymgoG08LaVok2Ajzj3waEnldmImL9qJraCcJSLmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYUJCT1VqblBYdHN5bzNz
            UE8zcmw2WHhhOGRDVmd1dFV0OXloWkZtdTBVCjVOa09LcVB3V2JoSVBmUzhNSVZL
            cGhoSjNxSkY2MnlpNy9UVFVkTWFqTnMKLS0tIHdLWlNHQmdIcHpGUmk4WWJvbCtx
            Y25aRFZCK3BLQ2g2UWk3R1VCQStjUmcKOXPC6VzasmWLY+gDgSd5xpMVkRk7o8an
            0CfuhahXSH9U6DcmMr4Hi3h3vzyTtgDORdtRqW4ERBURususO55KXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:05:02Z"
    mac: ENC[AES256_GCM,data:gkb6BMWBecLvSe8leuj5eS5AvCiU5NtGCnkeD584Xq2YPKu6ZD05QueD4YDL5AXG62zFSVhVAFzMvrRyIsUuRFt12RQ5OFR4ifCz1HYbhHB7zDXQFE9FM/6TDyhMm+p5Kr8FhdGHcgsl4hi9QP5agUmm7SGS9Y0ZNRBUr1Hq+GA=,iv:Gqys79XqHmZe6Y4yCHkNifDHRNdKJLvZHXyR5glFwDg=,tag:88mZHgnkOIHnZ6QILAj0Lw==,type:str]
    version: 3.13.3
