apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vaultwarden
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:KHQekNSDycqdGKz6GCs23IzaqMCVqmFm6pUFHDi623mV7+OptPhYh+EP5e5qHdzCerHDyt42bCdQvp3cNs2uRnD7wtmxaEEcDa0BJDPGbmgwWJNQ9fUwNuXt7AEo+PKmwnzKjn2E0y5XcTHTJtEybrsOD8vzsA==,iv:lBkEuNYr+ar3d4J25X1PoRijyFCU8z8Hodg0kmL+1Qg=,tag:dsiAFlJWFPAnLSG45DZuFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYmNZMnJKMTVZOG9QYUNC
            OElsd1ozK0FvNWpWVGd1dVJkNk1TeEd3RlJVCmZHOXM4cW1Pekx2QVJseWtNU2ps
            aFF6OWVDaHpVUTZ3UkJSYUsyd0VjTW8KLS0tIHlqUnZUaWZhYXlwZnAvNFNCTXQ2
            NkRoNW8vS2ovK2lWUkU1N2lJQVVLRVUKOhEWCgbhwHklOw26HwZOVdCbiBwhm1PL
            TKyISx1fidM30BoXGulKbEfvdX9r5XW4JU9j+KGpPLqsOwnPa4edog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSmR0dUlOUDc3SWVvcVpu
            QWhhbFFvRTQ4eE05Z2t3M2hHMFN3bEJvSUJnCkFXSllsZG9QS0luSllURURnVHVQ
            d29uSlBYamFmYjA5OGJOVXJhclV4Y2MKLS0tIGhRV1BYNFJZVlZxZFdFUjdON3BR
            WU5vVVJhcDhSclpIVFMyVGVRdE5TbE0KdYiNWS46DMkYolHNuW5E4YwAXme5j7QO
            EiinWIrDzDKAW/NNGSX+Akm/NmX87l9S2UAnuWaP80GFD+ovEgEvZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T03:32:29Z"
    mac: ENC[AES256_GCM,data:iino3s5bucvrdX+mPiQZsDD5yEOd5D/1jLh5qsnrRItjlF8nziZlyIBFXPNqvxgaWI15zjQIb6/3dmlkeBilVcmVV7/RHcy1X2OXZ23+538juOrIIhjnQwV8aL4JPacHtAP9sq1QvZ/YxvR0L0KkKDNSRI6+nEC9KE/hACLW9DQ=,iv:9vRUbzmm5JcxbsyTQnIFDKD1RwnFB4GF/iDflPITX/I=,tag:6Ng7jG02vsTSuLDJXZeaXg==,type:str]
    version: 3.13.2
