apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: cert-manager
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:C0zsLZE9AJ+YfMSkiVYmCevkpfw=,iv:8E3K8W4ej8n5NvEOiaHKa40NfY47oJQAU9yOpZNJEVg=,tag:98/NrvEIWgT/NK4E51jNsQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:FLGGiwIZigues3DgHU+NJhOI+R0uoXfIcGL7+vZH9C8IsYPVFUutKA==,iv:vNJEdZVSO5pL2bOBFEvgjRWDTzmwoZ4hBQ1IkeR8gKQ=,tag:1ltTcLQ6iX7KhmHdPOUI1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRzdHTjNrLzVCamNqT0k3
            YnkyOXljcTdjSlVFNHQ1bm1yTXBkZVh1R0VjCmlkS2J1SzJXYWNYNUVGciszOFZL
            VThaUGxZbXVlTHlrV0J1RllWNnZBQ1UKLS0tIFVBdG5CajZOTExPdFdDQ3V6NjY0
            OUMzQTR0eU5pSjU5cEc1N3FZWWxkN28Kx+86dYi6PISn9jx31QXuidmbwkrXQHJW
            JM6bUwRJq1VGDMP9E+NPH8XN5gZGeZ8b3RHcExbMaJqml/xuuC2gmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ0RSSS8yb1dPaloxaVFa
            NlNuZFM0RWlqcmVhUzRBN0pXQlhWSy9iaDA0CklTckxmL1M4OGwwY0JtOVJwNkFx
            Y2ZkaGFUbXhoUjZWS1lOc3hWc0ttaUEKLS0tIEFWUDNMeGJqT001R2tpN2xJeHZ5
            LzlzcE44anVDQ3RMYjgxanlQb3RpbjQK5BnNco5nls/HxaQF3qqozRF9g+ZxjKP7
            2XCjzvrAv/lNHd3wJEmpapsa1EXQ4cweSk1edJC3gIoZVRGKBJdK3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T22:32:32Z"
    mac: ENC[AES256_GCM,data:pjwTFMNwUpBhfdTbQz+adpUScIv7dq1sH5vZU0CdZogFiVUOiBwOCzV0DhMcNfbqjXoz3ai0zCANe5qIp0+uc62otFCrb7gQGd1zkqJx9A967zTRKSg3N0T4XIne0W1xQEFU+Pv6sFISyqFRCQGjv345QVV/90EsYMive3SWFKY=,iv:mNN0HCClirCAb/Xsct+JjQgscQYOF0gB1zMPn2ohJJ4=,tag:+HXVLWKG0We6URNoy56A7Q==,type:str]
    version: 3.13.2
