apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cilium-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-agent
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cilium-operator
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cilium-envoy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-envoy
  endpoints:
    - port: envoy-metrics
      path: /metrics
      interval: 30s
      relabelConfigs:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
