apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-standard-trixie
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie@sha256:f89a40f4d74aa6e0900917eaf6299b125a6382eb02fd4ee5d46f55bcbf7e5726
