apiVersion: v1
kind: Secret
metadata:
    name: ddns-aws-credentials
    namespace: ddns
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UMZ/3NABFuMPq3kaFaWCWOyzpzo=,iv:NsAGhsX9q23dNXsCYiNhm6HAC4pXFfIPdY+cOrFlOY4=,tag:8J1T2SLUcNwfbD+G9TIndA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1bzw96Kzw/kQodx47BnE/r/MX5S6w2w+UWJ5phHIi4RP3DW/gx/vvA==,iv:3aM4MUuhBfdjGTpziQXlw/FinfGAqYWRJUjhThLEJuY=,tag:cpwZpsrfcvav+t7G2q+yNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeWQwWURaMHZnLzZaQzls
            dDVOeG8xa1lqQUFWVnFwNEVzU0toci8zazE4Cm5rUjVoVHBOZTJoSUc5L1FDTmtl
            ZktMVzc5QWllRFFuL2tYK1VySElESUUKLS0tIHBWYXFpS29JT0xKYjBpQjI2eXR4
            eVlEZVZNdUJOaFVqTmYrakxMSDJUWHMKXBIJ4HeHRTvbt+LJ+COFMkPp+dazXLNl
            j4HhEyYeLCNbkWFNJUxaFDGUR1QFGUpG9BYbqzm0AjQV1KPj8y3c6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRnVXcnQvWmNEcDg1eTUw
            aUl4TzZsbjZPeWR6djJRZUV1WUFKUjRnUEVrCjhCVk5HOFIyUzdQYnZpUFExcEF1
            TitJYWE5eDdQSDVKSGNGM3pDTkowRUkKLS0tIGd6WWJITmg5UTFORkl5dlZzMUpY
            Q05ibG02Tm1kYjFLTUE5cVI3UW5lME0Kvcmlzou0XMi+0uOngK76jzoCwGcpL8YS
            cmIGvd/uuCQ/nJW29GEECcG+ZVFkkk6l1BLgUgSpAsaJgll61UrKGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T12:35:56Z"
    mac: ENC[AES256_GCM,data:MmYvCuBir5Mm+yRm10F51p1icZvoF1r2L7fhZH3vHLTui6Bc/UK+JD7sEBskqICqQJeTwj73aBCaK2YMf/QLjPvMIXPOKspOStoM7zuj0IA4BiZ9JXJXC96zStC1SNFE6zTDxr2SdXiCjsPVCAeu7cox0Cwf7i2aSzxtIxmfVeo=,iv:XsyHYGEZvZwHKU7EK5rhiVAQ/AvPyB1zTAcbvFJ0GwQ=,tag:HjHAQIdJpX0tP9deVlc6+A==,type:str]
    version: 3.13.3
