apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: survival-1-
labels:
  - pairs:
      mc.lilstrudel.io/server: survival-1
    includeSelectors: true
resources:
  - ../../base
  - network-policy.yaml
patches:
  - path: statefulset.yaml
  - path: service.yaml
