apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "1.21.1"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 1h
  values:
    provider:
      name: aws
    policy: upsert-only
    domainFilters:
      - lilstrudel.io
    txtOwnerId: homelab
    env:
      - name: AWS_DEFAULT_REGION
        value: us-east-1
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /etc/aws/credentials/credentials
    extraVolumes:
      - name: aws-credentials
        secret:
          secretName: external-dns
    extraVolumeMounts:
      - name: aws-credentials
        mountPath: /etc/aws/credentials
        readOnly: true
