apiVersion: v1
kind: Secret
metadata:
    name: external-dns
    namespace: external-dns
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:hKiSA/Fzz06/2XHsDOG2sntTriizFBdnSqJg8zubE+AAUNMms16uAqoXXx71MUx6RrdgwOA3CLBINmLKX/+HqPKzSp7TE7XFxE+FunMXKUzu4/wT4Vhv9BEO+Ivg1jc8a7HO8NN6YfQgheQaOSxCC0T/dio=,iv:IItc0tcO2DSwxkqHUg1JxKnq1QTfM8HDTqgLmm17oPc=,tag:/cpCbZ1PGKRfG4X1HgnBxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieWdncVRJMkNEYXdhQ0Q5
            cEJyRHptMVFWZjhHL3FPbUo1K0ljTG1MK3pFCmRKZWJLWU16a1JHbU5RVlg3dFRx
            bjYxZWdHNjJHRUd5YTF6WEl4N3VjOUEKLS0tIC9qTjdsRzBFSE5nMDBHclY0WnNv
            ekRraWE4QjhHNHF5WkdLOGloQkdnMEUKx3y6L6eJCXZQvALLw/zHPF1ink0CwU0J
            Pk2pFKLpaObuo/Mx1EddO1divAmfwv0lZJEBtp9/F/hAWy6s9m5wmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aEZCMkNsaDB3Sk5hT2RY
            TTQrKzFQRzQ4S0kyYThNSHUzUjllOEMrazA0CmhNTVliN09JMUJ1WDg4empGRmZp
            NW01S3dpRWxrWkZqbWtsT0U1N0ZqYkEKLS0tIFJ4Z0JaUXhLNUx3MFlXdzBFdm5a
            VEtiNkdNTnMxYURIM282NVhIeEd2d3cKFvcme9hzcAmn2zl/urwL3p7D5F5vJzhx
            EsD9AG+YceZlRnQ+Qk7XDRb5nKLYiU+6Uu5eWC10uehhlfTbq6ylZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T22:31:56Z"
    mac: ENC[AES256_GCM,data:4FAYOiPvQAyNvtX4JpPlVpi0EasRaNvC2eFcQ69aSadH1fgor+OPUbM3Xgdv9e8jni+Qe47cpkWxWsylCXLVME4jl4LWBf8sJ54XK7jJ1gt/GE1Z3qPc/qgNZohay8/IalIXyOchAsvB9JzEVVnobOSYS+odWXPNovZVcKPlQo8=,iv:pARRY2iUe9DVw1BRDFTdotHQFLJTdqTGey2gcmysWLc=,tag:He5eGvWuUxeMckbve7MG1A==,type:str]
    version: 3.13.2
