apiVersion: v1
kind: Secret
metadata:
    name: immich-pg-backup
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:kNye82lFenWp38ILYpuJ+aiNtSk=,iv:gXyAD+CU+ZZFzDiq8gfLI6n9TXEUlS7SX19Yy6RSNUc=,tag:GgGot5MIu0XQtpIuMebd3A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:fizxHSY7MxM02dqXfbB+3J9J7y3u3jbHV59bTxCuvoejWo6S1loOBg==,iv:5+57I3ck+KVpYFmWeyGKQaOjOLZNHJD6Rs5iLCTaeFQ=,tag:0Re9xgIxzuE0j7QkEAxgeg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:K0lOxSu4ERKt,iv:d5at22qA24HTIWLss1WfIh82/swRMqMFXkTguZ7bxPk=,tag:odlUDlz3yXuCb6XkfVbEgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eHM3QUIzVHd5ZWpQbFh3
            WFlDdGs0SEJqZ2FOZ21YQWxEQlJuamRwTFdRCjRNWlkrRDJuWGNpYm5ob3JRVzNh
            OTZtUzRyTmkyYWdyZTAzcnNML3JWN1EKLS0tIDBVaFdPeUVmMy84WW9YNUxPM2hl
            RkZMZjNIU0tCN1JCc2JNU1Jidk8zM0EKIjqJKQB6Ptenw8ABvyKNQXVIbxJwLpec
            8PTx6GpibPjiPZbgHk70Ut8QNT86QZRkqeOMS8Vi7RcjS22RZr5qZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeE1pNWZvRWNvUWZGejBH
            MEM3OStQZTJVWS9LelhuWnU4WTRXc1hZRkhZCmZiMUovNXNhZDNVdFpkNUs5ejlK
            YUVjT2c2SnVXMEhzeGs5a3dVUC92S3cKLS0tIGFnNklLZElTMmo3cDFQZmhNbFJU
            bjEvUk1IdFFJeXo2bWFuVnp1OVVPM3cKjQzPhmpkPcsV48GGCMvGVGYDNfA2rjsE
            1USKyZ5YwdHNX5f42O6tyx9fjgvBfKcSWuk6S0zpfXi4MzsNbi3Hbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T23:17:13Z"
    mac: ENC[AES256_GCM,data:118gDjDQYHQFIE12a9+7kLiPhAtSMDMlAx1hOE0Wte/o9oLg538yaA+rdz9Xa9nYg2o0MmdAcnn8dc2XraFHvsMcZjBRkY8+zD/KeFcI2fS+tT+LXVH3s6OJgB7ikCGOdT4j7iRkjLJ3LW3zRa9j+mKW7WwxKzppbyET4LwnJl8=,iv:cfq0JgI0x3hxOUqQmPW8rknegSu6JM3KIYSZN9OWq8k=,tag:26x7oU9tLNaX32WCyycXLg==,type:str]
    version: 3.13.3
