apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: immich-pg
  namespace: immich
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: immich-pg
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
