apiVersion: v1
kind: Secret
metadata:
    name: shlink-pg-backup
    namespace: shlink
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:vbN+Fzz40QNHzrkHvzsnjJjFTbI=,iv:TjaAc6KnH/tJ7/yXyN6L7+uRm7uJK1RY64xAxEZ8d0w=,tag:mQXeFPGCanr25GAySwfiGw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Wi6SRrtNXIASNYfd1Ltm7xT1jok9gwdjcnWPY/MxufP5NRO6e5Wnow==,iv:QakoL+YqvDRs/yEhjwF0ia7qO8MEutbZUDo6P9QXVxU=,tag:P2nSfNmAb3bHh8YB2odE+g==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:kR8VTcq7TZpI,iv:zsfMXyi2l72tLC6mCz4kDJIP5KTF7b7z95UZykqh4BQ=,tag:snmzAKGdoWu+P0FRPx6Cvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuazU3TUhpYzZuR1VNTDZD
            dGNkUC9mK1UvVG5tSVB0V041djNIM0ZvQUhzClpSU1kycVNocTgzcGZiZUw2RXNh
            UXozVkNWQXhEZ04xNEdiK2plQU5CcmsKLS0tIFlGanlFNnRDTkZXd2xoZ2k2QWlx
            WFRwTnNXWjAwa2U5WjZXRG1HWkhITWcKA4yeqTYOxIaiVEvmJ0MsGeC+W2hwsBhG
            D6QUxFHaXy4GXegZGiUTHpl8bfGJ8OflS4oJkE7ezGPt6zvUos2GHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMXFCREdCeFNISitXaXhr
            K3Y2TG9PSi9adTY4QnVnRGRzR0t5WnNua1JrCnk0Q04rWFlwc1pTMStYcWY3ZC9E
            angzMlpEOUxWTExHMVFjWVZWL0dyTWsKLS0tIE1JZGRieUltanhVdTMrMlcwQzN4
            aXp5OU5vL014Y0dtbFViSzgrZW84MlEKq+Bj2pqAyqfD97jWvIX17jnHlj6Snkoj
            sDe+HmvfVPhRMs05vL2JPp4+ZlmTQZw102efW3gNiZNjm3ZWbU3yIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T03:06:06Z"
    mac: ENC[AES256_GCM,data:hIvu9I3eQOv/3/HwnHZM11KQXBawSGuCec7OwtOr9KKWGhlkA6B4n97t3aDlbEzFZpIzOasGb/yYeZTmLtoe6lmfzW8A1FDrs/Jkjlgzyn2U9b3q8UWuLjDmXdXcbVyQUWgS24JWJMs59E0w8g/+Z1/G5Mdca5Y/QAT4UqFVX4I=,iv:nGb9lF6Ysm7aQb6uBRyamch1ymn7b1k3V2TlA5Tdt28=,tag:U9F6ZQ67pcnjeNX0Fqsdbg==,type:str]
    version: 3.13.3
