apiVersion: v1
kind: Secret
metadata:
    name: shlink
    namespace: shlink
type: Opaque
stringData:
    INITIAL_API_KEY: ENC[AES256_GCM,data:mB/Eohn2IwIUYUz8Nrfj5x/nn43IUXF15uOSw/VU2aJ8N8cO,iv:dC0y62n7rTjRv8xVZzgRjyyv9OWsC/S8Bly+5ygY6+0=,tag:+ll3ZLHJ0K8ThfXkOT9FJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVllnaFhHVEVubzhITlRi
            Q1NOQ2pDTldiWWZCOWNZcXZ0RFVYT1B3SEVZCm1tWlNSd1lTM29HanRMQXFsNzBS
            ZHQrb0NCSVNUNnlqZmlwa1Vsb3grNzAKLS0tIGd2NUdGcHh1QzlISjkrMURpT1ZT
            NzJubnV1N0lzS3l3dDFFZE4yaTU5QWcKBEmhiByW7jtrrh5/ul62BNI0CGWzz1dB
            fH6tXTQ4tv/wPNjE/cRHU0ZxzQMeS8qZLhdyavKYMqxhMTJge2a97A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dhzh7r7c8u8sqdfrpdupk6r37zyk9m6yha3x37964u72rg4degtqy8pzp5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLa0puTS9Uckg2Q2FpYmdK
            Y1dSTkkrQytYMGRUbjJIc0s5bG5JaW5IM2tnCkptbHNMVmdoK3Z3YXlFcG5UVk1V
            NGt0d1JCSFlLZ0o3ejI0TzdOZDBhakEKLS0tIGd1NHJ6andWZDZZZUhTcGRpNGl1
            NlJpR1d0R0VQK0RpR0JwMFNUOWJqT1UKCuHHxX+/O4wvaDZT8nZgpVgKhk0c0p/A
            ryKDtSnDoMRLax1t+tvfo3nIMBV+BUzZIwQK8lWXjhNJe6Lev/aYuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19etvk27ryx8ksye4r2pghvqd3ml2f6aqgrsahn5c2tm5hxq5ha8sj88fwd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T22:44:47Z"
    mac: ENC[AES256_GCM,data:W/9PtYoz5KSyGKkeJ6V8qD2RiGN5q3ka7WKyzvr+fymNx3ElCQJ38VAZOKxONncQEiEVck5o9wHffghcw+fAHT+WD8tAwd/VWD1Eq0p7tfnUNCDbsRoj8kFHKYAXtZ4Q+Gwx5+LXpx3Zn82pljFko1C1wvOQH/ZRWWXv8tAoBa8=,iv:guVv2G/5xfD7reXbFTvGnuKKzViKCzZ1v+V2QAl8WAc=,tag:8m+GJTpGutG4dkUqP2j0Ng==,type:str]
    version: 3.13.2
