---
apiVersion: v1
kind: Service
metadata:
  name: p-mc-service
  namespace: default
  labels:
    app: p-mc
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
  selector:
    app: p-mc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p-mc-claim
  namespace: default
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p-mc
  namespace: default
  labels:
    app: p-mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p-mc
  template:
    metadata:
      labels:
        app: p-mc
    spec:
      containers:
        - name: p-mc
          image: itzg/minecraft-server:latest
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: p-mc-claim
